env:
  global:
    - PGPORT=5432
    - NODE_ENV=development
    - DATABASE_URL="postgres://postgres:''@localhost:5432/travis_ci_test"
    - TEST_DATABASE_URL="postgres://postgres:''@localhost:5432/travis_ci_test"

language: nodejs
node_js:
  - '10'

services:
  - postgresql

before_script:
  - . $HOME/.nvm/nvm.sh
  - psql -c 'create database travis_ci_test;' -U postgres
  - nvm install
  - nvm use
  - npm install
  - npm run build
  - npm run migrate-tests
  - npm run seed-tests

script:
  - npm run test -- --forceExit --detectOpenHandles
  - echo 'Finished running travis script.'
